version: '3.2'
services:
  api-service:
    image: ./api-service
    # build: ./
    ports:
      - "8192:8192"
    volumes:
      - ./config.yml:/home/nodejs/config/config.yml
    environment:
      - NODE_ENV=production # help to improve node.js performance
    # deploy:
    #   placement:
    #     constraints: [node.hostname==swarm-manager1]
    #   restart_policy:
    #     condition: on-failure
    # command: node --inspect=0.0.0.0:9229 app/index.js
    command: node app/index.js
