# JSON schema in Yaml
$schema: http://json-schema.org/draft-07/schema#
title: Dashboard Service Config Schema
type: object
#additionalProperties: false
required: [name, express, mongoDBs]
properties:
  name:
    type: string
    default: 'Dashboard Service Configuration'
  type:
    type: string
    enum: [local, proto, test, prod]
    default: local
    description: building type
  case:
    type: string
    default: bf
    description: building condition for different case
  # HTTP server
  express:
    type: object
    required: [port, protocol]
    properties:
      port:
        type: integer
        minimum: 8100
        maximum: 65535
        default: 8190
      protocol:
        type: string
        enum: [http, https]
        default: http
  # database
  mongoDBs:
    type: array
    items:
      - $ref: '#/definitions/mongoItem'

# reuse components
definitions:
  db:
    type: object
    required: [url]
    properties:
      url:
        type: string
        sample: mongodb://localhost:27017/dashboard
      username:
        type: string
        default: admin
      password:
        type: string
        default: admin
  mongoItem:
    type: object
    properties:
      name:
        type: string
      url:
        type: string
        sample: mongodb://localhost:27017
      username:
        type: string
        default: admin
      password:
        type: string
        default: admin
      dbs:
        type: array
        items:
          - $ref: '#/definitions/dbItem'
    required: [url, dbs]
  dbItem:
    type: object
    properties:
      name:
        type: string
        sampe: dashboard
      collections:
        type: array
        items:
          - type: string
    required: [name]
