# config in yaml
name: Dashboard Chart Service Configuration
express:
  port: 8192
  protocol: http
mongoDBs:
  - name: main
    url: mongodb://10.193.8.72:27022
    dbs:
      - name: raw
      - name: da
      - name: dashboard
        collections:
          - pages
          - metadatas
          - categories
          - histories
mongoDB:
  raw:
    url: mongodb://10.193.8.72:27022/raw
  da:
    url: mongodb://10.193.8.72:27022/da
  dashboard:
    url: mongodb://10.193.8.72:27022/dashboard
uaa:
  url: http://10.193.8.72:28085/uaa/api/v1/service/hasAuth
kafka:
  type: zookeeper
  urls: # if type is zookeeper, only first element will be used
    - 10.193.8.72:2181
  updateInterval: 30 # in seconds
  topics: # define key string in topic name for filter
    - raw
    - RAW
    - Raw
